### PR TITLE
Feature hic scaffolding

### PR DESCRIPTION
**Pull request by mahesh-panchal**
- Adds Pixi development environment
- Add Scaffolding Pipeline.

### CODE REVIEW

**Comment by mahesh-panchal** [comment]
Oh, and since I'm the one making the PR, you're the one who needs to approve so we can merge.

**Comment by mahesh-panchal** [comment]
My apologies for adding more commits, but I addressed my earlier comments, and fixed the report ( I hope ).
Hopefully you can then focus on the final fixes you want to make.

**Comment by mahesh-panchal** [comment]
Bah, Bird plots look messed up after "fixing" the notebook. Need to check again.

**Review by MartinPippel — APPROVED** [review]
Pipeline runs through now and creates reasonable maps. Therefore we should merge it now into the main branch. 
The wasp was not a good test case as the HiC maps also look odd in the DTOL publication https://wellcomeopenresearch.org/articles/8-461 
We should quickly add more features: 

- create multiple pretext-maps with different mapQV thresholds - and with/without demultiplexing
- add more statistics about HiC quality 
- move the mapping parts (from scaffolding and map creation) into own subworkflows

**Comment by mahesh-panchal** [comment]
OK. Agreed. Can you select a better full scale test then than the wasp?

I'll work on fixing the scaffolding merqury plot though to start in a new PR.

**Pull request merged**
