### PR TITLE
Make execution report default

### PR DESCRIPTION
**Pull request by mahesh-panchal**
- Makes the execution report and trace on by default rather than an extra profile.

### CODE REVIEW

**Comment by gbdias** [comment]
I just updated the repo to the latest version then added your fork as a remote to try the default execution report. I get an error within minutes of execution. I don't think it's related to the profiles_patch though, but since there are so many changes since I last ran the main branch I'm not sure what could it be. Did you get this before @MartinPippel @mahesh-panchal?
```
Jun-17 09:42:54.867 [main] DEBUG nextflow.Session - Session aborted -- Cause: Missing `fromPath` parameter
Jun-17 09:42:54.947 [main] DEBUG nextflow.cli.Launcher - Operation aborted
nextflow.exception.AbortOperationException: Missing `fromPath` parameter
```
The command:
```
# Run Nextflow
nextflow run "$NXF_SCRIPT" \
    -profile uppmax \
    -work-dir "$WORKDIR" \
    -resume \
    -ansi-log false \
    --cache "${STORAGEALLOC}/nobackup/database-cache" \
    --outdir "$RESULTS"
```
The parameters:
```
# Mandatory - sample metadata
sample:
  name: 'Tetrastemma melanocephalum'

# Optional - HiFi data if available
hifi:
  - reads: '/proj/snic2021-6-194/BGE_Tetrastemma_melanocephalum_assembly/data/outputs/trim_reads_45378607/tetrastemma_hifi.clipped.bam'
```
Repo version
```
(nextflow-env) [guibo205@rackham1 Earth-Biogenome-Project-pilot]$ git status
HEAD detached at mahesh_fork/profiles_patch
nothing to commit, working tree clean
(nextflow-env) [guibo205@rackham1 Earth-Biogenome-Project-pilot]$ git log -1
commit e74a9c32f36d13621f744ea5ed96fdc6ddfc813a (HEAD, mahesh_fork/profiles_patch)
Author: Mahesh Binzer-Panchal <mahesh.binzer-panchal@nbis.se>
Date:   Fri Jun 14 15:19:42 2024 +0000

    Make execution report default
```

**Comment by mahesh-panchal** [comment]
Where are you supplying the `params.input`? I see no `--input` or `-params-file` in your command.

**Comment by gbdias** [comment]
oh right, I deleted it by mistake when removing the execution_report profile parameter. Trying again, thanks!

**Review by MartinPippel — APPROVED** [review]
I tested it and it's working! 
great idea! I really like to see the trace file. I have never provided the execution_report profile, which include the slurm IDs as well.

**Comment by gbdias** [comment]
Maybe we can merge now then. I'm having a hard time testing it because: 
(01) long queue time for high mem nodes, 
(02) failure in processes causes everything else to abort (then back to the queue again...).
I think we discussed this before, but it would be nice if all processes are executed unless the required input files are not presents. i.e. Perhaps processes that do not depend on MitoHiFi results should not abort when MitoHiFi fails.

**Review by gbdias — APPROVED** [review]

**Comment by mahesh-panchal** [comment]
I'll work on that when I'm back.

**Pull request merged**
