### PR TITLE
Add Dardel profile

### LINKED ISSUE #59: Dardel profile
**Is your feature request related to a problem? Please describe.**
Rackham is coming to its end of life

**Describe the solution you'd like**
Add a profile similar to the nf-core profile

### PR DESCRIPTION
**Pull request by mahesh-panchal**
Closes #59 .
Adds a Dardel profile based on the nf-core pdc_kth profile.

### CODE REVIEW

**Comment by Estel-Kitsune** [comment]
This is what I get when I try to run the pipeline on dardel:

```
(/cfs/klemming/projects/supr/snic2020-2-25/nbis/assemblies/nextflow-env) [estell@login1 01_assembly-workflow_initial-run_rackham]$ bash run_nextflow.sh
N E X T F L O W  ~  version 24.04.2
Pulling NBISweden/Earth-Biogenome-Project-pilot ...
 Already-up-to-date
Launching `https://github.com/NBISweden/Earth-Biogenome-Project-pilot` [confident_sinoussi] DSL2 - revision: a35d604a60 [dardel_profile]

    Running NBIS Earth Biogenome Project Assembly workflow.
    
Staging foreign file: ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz
ERROR ~ Error executing process > 'DECONTAMINATE:FCSGX_FETCHDB (all.manifest)'

Caused by:
  Failed to submit process to grid scheduler for execution


Command executed:

  sbatch .command.run

Command exit status:
  1

Command output:
  sbatch: error: Batch job submission failed: No partition specified or system default partition
```

My launch script:

```
# Run Nextflow
nextflow run "$NXF_SCRIPT" \
    -r dardel_profile \
    -latest \
    -profile dardel,execution_report \
    -work-dir "$WORKDIR" \
    -resume \
    -ansi-log false \
    --input assembly_parameters.yml \
    #-params-file assembly_parameters.yml \
    #-params-file workflow_parameters.yml \
    --cache "${STORAGEALLOC}/nobackup/database-cache" \
    --outdir "$RESULTS" \
    --steps inspect
```


The corresponding header from .command.run that failed:
```
#!/bin/bash
#SBATCH -J nf-DECONTAMINATE_FCSGX_FETCHDB_(all.manifest)
#SBATCH -o /cfs/klemming/projects/snic/snic2020-2-25/nbis/assemblies/male_skylark/analyses/01_assembly-workflow_initial-run_rackham/nxf-work/b2/3bdafc615a0ce11bfeda32a987c470/.command.log
#SBATCH --no-requeue
#SBATCH --signal B:USR2@30
#SBATCH -t 48:00:00
#SBATCH --mem 6144M
NXF_CHDIR=/cfs/klemming/projects/snic/snic2020-2-25/nbis/assemblies/male_skylark/analyses/01_assembly-workflow_initial-run_rackham/nxf-work/b2/3bdafc615a0ce11bfeda32a987c470
### ---
### name: 'DECONTAMINATE:FCSGX_FETCHDB (all.manifest)'
### container: '/cfs/klemming/projects/supr/snic2020-2-25/nbis/assemblies/male_skylark/analyses/01_assembly-workflow_initial-run_rackham/naiss2023-2-13/nobackup/ebp-singularity-cache/depot.galaxyproject.org-singularity-ncbi-fcs-gx-0.5.0--h4ac6f70_3.img'
### outputs:
### - 'gxdb_all'
### - 'versions.yml'
### ...
````

There is no mention of the partition in the header like:
``` 
#SBATCH -p shared
````

**Comment by mahesh-panchal** [comment]
The profile is called `dardel`. Thanks I forgot to update the README.

**Comment by mahesh-panchal** [comment]
Also don't forget the project allocation

**Comment by Estel-Kitsune** [comment]
I modified the dardel.config file (looking at https://github.com/nf-core/configs/blob/master/conf/pdc_kth.config) and it seems to be working . My syntax is probably not great as I am not fluent in Nextflow :-/  

I attached my config file.
[dardel_estelle.config.txt](https://github.com/user-attachments/files/15604516/dardel_estelle.config.txt)

**Comment by mahesh-panchal** [comment]
I made a mistake with the object type and it returned nothing as a result. 
Have a go now and see if this fixes it.

**Comment by Estel-Kitsune** [comment]
Yes it's working now!

**Review by Estel-Kitsune — APPROVED** [review]

**Pull request merged**
