### PR TITLE
Use channel helper in Purge dups workflow

### PR DESCRIPTION
**Pull request by mahesh-panchal**
- Use helper function to make assembly record.

### CODE REVIEW

**Comment by MartinPippel** [comment]
I think theoretically that's a very good idea. But in practice I have also seen multiple bacterial assemblies with duplicated contigs, mostly due to a higher error rates in some regions causing "spurs" or bubbles. Would there be an option to "force" purging for assemblies with ploidy=1? I guess setting ploidy to 2 would cause many undesired side effects (e.g. GenomeScope, etc.)

**Comment by mahesh-panchal** [comment]
Nah, you're right about that. Having to set ploidy is not a good way to circumvent this. Better just to let the user turn the stage off manually for haploids if it's not desired. Perhaps later I'll integrate turning off the workflow for haploids instead.

**Comment by mahesh-panchal** [comment]
OK. Limiting this PR to using the channel helper

**Review by MartinPippel — APPROVED** [review]
nice reduction, looks much cleaner

**Pull request merged**
